"""Aggiunto VALORE a Problema

Revision ID: 0c35b275ad2a
Revises: 14026b81ddef
Create Date: 2026-10-06 22:57:31.034976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c35b275ad2a'
down_revision = '14026b81ddef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('VALORE', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.drop_column('VALORE')

    # ### end Alembic commands ###
