"""Tolto valore_attuale da Problema

Revision ID: 14026b81ddef
Revises: 8605d8b119e1
Create Date: 2026-09-26 21:41:11.164790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14026b81ddef'
down_revision = '8605d8b119e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.drop_column('valore_attuale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valore_attuale', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
