"""Aggiunto start manuale a Gara

Revision ID: 8605d8b119e1
Revises: 
Create Date: 2026-09-21 21:43:23.225100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8605d8b119e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gara', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_manuale', sa.Boolean(), nullable=False))
        batch_op.alter_column('unix_start',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('gara', schema=None) as batch_op:
        batch_op.alter_column('unix_start',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('start_manuale')

    # ### end Alembic commands ###
